<a href="https://colab.research.google.com/github/cbowler1234/ECGR4090_Tabkhi_Hw/blob/main/Hw2/Hw2_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [141]:
import torch
import numpy as np


In [142]:
temp=torch.tensor(list(range(9)))
print(temp)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [143]:
new_temp=torch.sqrt(temp)
new_temp

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [144]:
new_temp2=torch.cos(temp)
new_temp2

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [145]:

import imageio

RGB_Green= imageio.imread("/content/drive/MyDrive/Hw2 images/RGB_Green.jpg")
RGB_Blue= imageio.imread("/content/drive/MyDrive/Hw2 images/RGB_Blue.jpg")
RGB_Red= imageio.imread("/content/drive/MyDrive/Hw2 images/RGB_Red.jpg")


In [146]:
RGB_Green

Array([[[ 52,  54,  49],
        [ 48,  50,  45],
        [ 48,  50,  45],
        ...,
        [ 28,  36,  23],
        [ 30,  38,  25],
        [ 28,  36,  23]],

       [[ 50,  52,  47],
        [ 48,  50,  45],
        [ 51,  53,  48],
        ...,
        [ 27,  35,  22],
        [ 35,  43,  30],
        [ 35,  43,  30]],

       [[ 51,  53,  48],
        [ 51,  53,  48],
        [ 49,  51,  46],
        ...,
        [ 29,  37,  24],
        [ 35,  43,  30],
        [ 32,  40,  27]],

       ...,

       [[ 46,  43,  36],
        [ 42,  39,  32],
        [ 52,  49,  42],
        ...,
        [ 99,  52,  26],
        [100,  53,  27],
        [ 96,  49,  23]],

       [[ 45,  42,  35],
        [ 38,  35,  28],
        [ 49,  46,  39],
        ...,
        [108,  61,  35],
        [106,  59,  33],
        [ 95,  48,  22]],

       [[ 48,  45,  38],
        [ 35,  32,  25],
        [ 42,  39,  32],
        ...,
        [109,  62,  36],
        [105,  58,  32],
        [102,  55,  29]]

In [147]:
RGB_Blue

Array([[[204, 140,  92],
        [206, 140,  92],
        [208, 142,  94],
        ...,
        [ 93,  44,  27],
        [ 88,  39,  22],
        [ 89,  38,  21]],

       [[210, 144,  96],
        [213, 147,  99],
        [215, 149, 101],
        ...,
        [ 81,  32,  15],
        [ 84,  35,  18],
        [ 84,  35,  18]],

       [[210, 144,  96],
        [209, 143,  95],
        [210, 144,  96],
        ...,
        [ 74,  27,   9],
        [ 84,  37,  19],
        [ 87,  40,  22]],

       ...,

       [[208, 143, 105],
        [215, 150, 112],
        [211, 143, 104],
        ...,
        [170, 109,  80],
        [175, 114,  85],
        [180, 119,  90]],

       [[207, 142, 104],
        [215, 147, 110],
        [209, 141, 102],
        ...,
        [175, 114,  85],
        [168, 107,  78],
        [162, 101,  72]],

       [[209, 144, 106],
        [212, 144, 107],
        [205, 137,  98],
        ...,
        [180, 119,  90],
        [176, 115,  86],
        [166, 105,  76]]

In [148]:
RGB_Red

Array([[[ 34,  44,  46],
        [ 33,  43,  45],
        [ 37,  47,  49],
        ...,
        [ 23,  34,  40],
        [ 21,  32,  38],
        [ 17,  28,  34]],

       [[ 32,  42,  44],
        [ 29,  39,  41],
        [ 24,  34,  36],
        ...,
        [ 10,  21,  27],
        [ 23,  34,  40],
        [ 22,  33,  39]],

       [[ 35,  45,  47],
        [ 25,  35,  37],
        [ 21,  31,  33],
        ...,
        [ 10,  21,  27],
        [ 18,  29,  35],
        [ 12,  23,  29]],

       ...,

       [[208, 200, 181],
        [204, 196, 177],
        [201, 193, 174],
        ...,
        [ 87,  85,  62],
        [ 79,  75,  40],
        [ 79,  75,  30]],

       [[205, 197, 178],
        [204, 196, 177],
        [203, 195, 176],
        ...,
        [ 84,  80,  45],
        [ 70,  67,  14],
        [ 82,  77,  13]],

       [[206, 198, 179],
        [206, 198, 179],
        [206, 198, 179],
        ...,
        [ 87,  82,  40],
        [ 80,  76,  12],
        [ 95,  89,  13]]

In [149]:
RGB_Blue.shape

(4032, 3024, 3)

In [150]:
RGB_Red.shape

(4032, 3024, 3)

In [151]:
RGB_Green.shape

(4032, 3024, 3)

In [152]:
img_Red= torch.from_numpy(RGB_Red.copy())
out_Red = img_Red.permute(2, 0, 1)


img_Blue= torch.from_numpy(RGB_Blue.copy())
out_Blue = img_Blue.permute(2, 0, 1)


img_Green= torch.from_numpy(RGB_Green.copy())
out_Green = img_Green.permute(2, 0, 1)


In [153]:
out_Red=out_Red*1.0
out_Blue=out_Blue*1.0
out_Green=out_Green*1.0


In [154]:
out_Red_mean=(out_Red).mean()
out_Blue_mean=(out_Blue).mean()
out_Green_mean=(out_Green).mean()


In [155]:
out_Red_mean

tensor(107.1859)

In [156]:
out_Blue_mean

tensor(143.7254)

In [157]:
out_Green_mean

tensor(72.6740)

In [158]:
RedChannel_mean_Red = out_Red[0, :,:].mean();
GreenChannel_mean_Red = out_Red[1, :,:].mean();
BlueChannel_mean_Red = out_Red[2, :,:].mean();
RedChannel_mean_Red="{:.3f}".format(RedChannel_mean_Red)
GreenChannel_mean_Red = "{:.3f}".format(GreenChannel_mean_Red)
BlueChannel_mean_Red="{:.3f}".format(BlueChannel_mean_Red)





In [159]:
RedChannel_mean_Blue = out_Blue[0, :,:].mean();
GreenChannel_mean_Blue = out_Blue[1, :,:].mean();
BlueChannel_mean_Blue = out_Blue[2, :,:].mean();
RedChannel_mean_Blue="{:.3f}".format(RedChannel_mean_Blue)
GreenChannel_mean_Blue = "{:.3f}".format(GreenChannel_mean_Blue)
BlueChannel_mean_Blue="{:.3f}".format(BlueChannel_mean_Blue)


In [160]:
RedChannel_mean_Green = out_Green[0, :,:].mean();
GreenChannel_mean_Green = out_Green[1, :,:].mean();
BlueChannel_mean_Green = out_Green[2, :,:].mean();
RedChannel_mean_Green="{:.3f}".format(RedChannel_mean_Green)
GreenChannel_mean_Green = "{:.3f}".format(GreenChannel_mean_Green)
BlueChannel_mean_Green="{:.3f}".format(BlueChannel_mean_Green)


In [161]:
print(f"Red Image mean RGB values {RedChannel_mean_Red}, {GreenChannel_mean_Red}, {BlueChannel_mean_Red}")


Red Image mean RGB values 149.722, 90.172, 81.664


In [162]:
print(f"Blue Image mean RGB values {RedChannel_mean_Blue}, {GreenChannel_mean_Blue}, {BlueChannel_mean_Blue}")

Blue Image mean RGB values 157.153, 146.281, 127.743


In [163]:
print(f"Green Image mean RGB values {RedChannel_mean_Green}, {GreenChannel_mean_Green}, {BlueChannel_mean_Green}")

Green Image mean RGB values 81.909, 100.762, 35.351
